name: cassandra
description: A Dart driver for the Apache Cassandra database.
homepage: https://github.com/thosakwe/dart_cassandra.git
environment:
  sdk: ">=1.8.0 <3.0.0"
version: 0.0.0
dependencies:
  dart2_constant: ^1.0.0
dev_dependencies:
  charcode: ^1.0.0
  test: ^1.0.0